### ISSUE TITLE
Make an awesome "created at" time-viewer

### ISSUE THREAD

**Issue by ljungqvist93** [ljungqvist93/danielljungqvist#2]
Like so:

< 1 hour ago - Less than an hour ago

1-5 hours ago - less than 5 hours ago

6 hours + - show date [ 21th of Jule, 03:53am ]

**Comment by ledungsbacken** [comment]
<?= human_readable_time_diff($post['created_at']); ?>

**Comment by ledungsbacken** [comment]
16e9ca6c66c28e9d19b7e705e01cd7f528b166b6
